name: Proxy build (Testing Farm)

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run build on Testing Farm bare metal
        uses: sclorg/testing-farm-as-github-action@v4
        with:
          api_key: ${{ secrets.TESTING_FARM_API_TOKEN }}
          api_url: https://api.testing-farm.io/v0.1
          tf_scope: public
          compose: RHEL-9-Nightly
          git_url: ${{ github.event.pull_request.head.repo.clone_url }}
          git_ref: ${{ github.event.pull_request.head.sha }}
          tmt_plan_regex: /plans/build
          tmt_hardware: '{"virtualization": {"is-virtualized": false}}'
          tmt_context: "arch=x86_64"
          variables: "SOURCE_REPO=${{ github.event.pull_request.head.repo.clone_url }};SOURCE_REF=${{ github.event.pull_request.head.sha }}"
          timeout: 60
